name: kitapp
description: Social Book App

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  #firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  google_sign_in: ^5.4.2
  sign_in_with_apple: ^4.2.0

  #cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #state management
  hooks_riverpod: ^2.1.1
  flutter_hooks: ^0.18.5+1

  #routing
  auto_route: ^5.0.4

  #core_utilities
  url_launcher: ^6.1.7
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  package_info_plus: ^3.0.2
  connectivity_plus: ^3.0.2
  url_strategy: ^0.2.0
  easy_localization: ^3.0.1
  supercharged: ^2.1.1
  recase: ^4.1.0
  image_picker: ^0.8.6
  permission_handler: ^10.2.0
  file_picker: ^5.2.2
  intl: ^0.17.0
  crypto: ^3.0.2

  #animations
  animate_do: ^2.1.0
  simple_animations: ^4.1.0
  lottie: ^1.3.0
  shimmer: ^2.0.0

  #ui
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.15
  gap: ^2.0.1
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3
  hive_generator: ^2.0.0
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#1a1a1a"
  image: assets/png/splash.png
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/translations/
