// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOclpFhCGH9wq_5EgepytXM-i0Nve8wiw',
    appId: '1:575750537711:web:860ff5408ca21a00c2761a',
    messagingSenderId: '575750537711',
    projectId: 'iuc-kitapp',
    authDomain: 'iuc-kitapp.firebaseapp.com',
    storageBucket: 'iuc-kitapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-zuMB2AnsSJE1gCR1tFwEpCnklNm11IY',
    appId: '1:575750537711:android:9a70d37fcbcfd10ec2761a',
    messagingSenderId: '575750537711',
    projectId: 'iuc-kitapp',
    storageBucket: 'iuc-kitapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgTrjuGZwjDnT2PtPXUUjkw-KyfGoaKW4',
    appId: '1:575750537711:ios:b3a09f5f78c30686c2761a',
    messagingSenderId: '575750537711',
    projectId: 'iuc-kitapp',
    storageBucket: 'iuc-kitapp.appspot.com',
    iosClientId: '575750537711-1aonmlusohvmhes78tv05k2s8tu4lsfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgTrjuGZwjDnT2PtPXUUjkw-KyfGoaKW4',
    appId: '1:575750537711:ios:b3a09f5f78c30686c2761a',
    messagingSenderId: '575750537711',
    projectId: 'iuc-kitapp',
    storageBucket: 'iuc-kitapp.appspot.com',
    iosClientId: '575750537711-1aonmlusohvmhes78tv05k2s8tu4lsfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitapp',
  );
}
